name: nominatim
description: Dart wrapper for OpenStreetMap Nominatim API.
version: 1.0.0
repository: https://github.com/moductor/dart_nominatim

environment:
  sdk: ^3.2.3

dependencies:
  http: ^1.1.2
  latlong2: ^0.9.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
